// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Compiler, Expressions, ScriptCompiler, exports, isArray, isRuleMap, isString, lib, parse, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./Utility').Utility, isRuleMap = _ref.isRuleMap, lib = _ref.lib, parse = _ref.parse;

  _ref1 = require(lib + 'Utility').Utility, isString = _ref1.isString, isArray = _ref1.isArray;

  ScriptCompiler = require(lib + 'Compiler').Compiler;

  Expressions = require('./Expressions').Expressions;

  exports = (_ref2 = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref2 : this;

  exports.Compiler = Compiler = (function(_super) {
    __extends(Compiler, _super);

    function Compiler(parseImpl) {
      if (parseImpl == null) {
        parseImpl = parse;
      }
      Compiler.__super__.constructor.call(this, parseImpl);
    }

    Compiler.prototype.parse = function(code) {
      var important, key, map, rule, value, _i, _len;
      if (!isArray(code)) {
        return this.parseImpl(code.toString());
      }
      map = new Expressions;
      for (_i = 0, _len = code.length; _i < _len; _i++) {
        rule = code[_i];
        key = rule[0], value = rule[1], important = rule[2];
        map.add(key, this.toExpression(value), important);
      }
      return map;
    };

    Compiler.prototype.evaluate = function(code, context, variables, scope, stack) {
      var map;
      if (context == null) {
        context = {};
      }
      if (variables == null) {
        variables = {};
      }
      map = this.parse(code);
      return map.each(function(key, value, important) {
        map.rules[key] = value.evaluate(context, variables, scope, stack);
      });
    };

    Compiler.prototype.ast = function(data, callback, compress) {
      var comp, rules, save, self, tree;
      if (compress == null) {
        compress = true;
      }
      rules = isRuleMap(data) ? data : this.parse(data);
      self = this;
      save = this.save;
      comp = this.compress;
      tree = [];
      rules.map(function(key, value, important) {
        var ast;
        ast = save.call(self, value, callback, compress);
        tree.push([key, compress ? comp.call(self, ast) : ast, important]);
      });
      return tree;
    };

    Compiler.prototype.stringify = function(data, callback, compress) {
      var important, index, key, opcode, rule, value, _i, _len;
      if (compress == null) {
        compress = true;
      }
      opcode = this.ast(data, callback, compress);
      if (compress) {
        for (index = _i = 0, _len = opcode.length; _i < _len; index = ++_i) {
          rule = opcode[index];
          key = rule[0], value = rule[1], important = rule[2];
          key = JSON.stringify(key);
          value = "[" + value[0] + "," + (JSON.stringify(value[1])) + "]";
          important = JSON.stringify(important);
          opcode[index] = "[" + key + "," + value + "," + important + "]";
        }
        return "[" + (opcode.join('],[')) + "]";
      } else {
        return JSON.stringify(opcode);
      }
    };

    Compiler.prototype.load = function(data, compress) {
      var code, important, key, opcode, rule, value, _i, _len;
      if (compress == null) {
        compress = true;
      }
      opcode = isArray(data) ? data : this.expand(data);
      code = [];
      for (_i = 0, _len = opcode.length; _i < _len; _i++) {
        rule = opcode[_i];
        key = rule[0], value = rule[1], important = rule[2];
        important = important ? ' !important' : '';
        code.push("" + key + ":" + (Compiler.__super__.load.call(this, value, compress)) + important);
      }
      return code.join(';');
    };

    return Compiler;

  })(ScriptCompiler);

}).call(this);

/*
//@ sourceMappingURL=Compiler.map
*/
