// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var ExpressionMap, Scope, ScriptScope, exports, lib, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  lib = require('./Utility').Utility.lib;

  ScriptScope = require(lib + 'Scope').Scope;

  ExpressionMap = require('./Ordered/ExpressionMap').ExpressionMap;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Scope = Scope = (function(_super) {
    __extends(Scope, _super);

    function Scope() {
      _ref1 = Scope.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Scope.prototype.create = function(operator, parameters) {
      if (operator === 'rules') {
        return this.addRule(new ExpressionMap, parameters);
      }
      return Scope.__super__.create.call(this, operator, parameters);
    };

    Scope.prototype.addRule = function(rule, parameters) {
      var expression, important, key;
      key = parameters[0], expression = parameters[1], important = parameters[2];
      if (expression.operator.name === 'list') {
        expression = this.create('group', [expression]);
      }
      return rule.add(key, expression, important);
    };

    return Scope;

  })(ScriptScope);

}).call(this);

/*
//@ sourceMappingURL=Scope.map
*/
