// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var RuleMap, UnorderedRuleMap, exports, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  UnorderedRuleMap = require('../Unordered/RuleMap').RuleMap;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.RuleMap = RuleMap = (function(_super) {
    __extends(RuleMap, _super);

    function RuleMap(sequence, rules, priority) {
      this.sequence = sequence != null ? sequence : [];
      this.rules = rules;
      this.priority = priority;
      RuleMap.__super__.constructor.call(this, this.rules, this.priority);
    }

    RuleMap.prototype.add = function(key, value, important) {
      var exists, id;
      id = this.normalizeKey(key);
      exists = this.rules.hasOwnProperty(id);
      if (!(important === true || exists === false || this.priority.hasOwnProperty(id) === false)) {
        return this;
      }
      this.rules[id] = this.normalizeValue(value);
      if (important === true) {
        this.priority[id] = true;
      }
      if (exists === false) {
        this.sequence.push(id);
      }
      return this;
    };

    RuleMap.prototype.map = function(fn) {
      var key, _i, _len, _ref1, _results;
      _ref1 = this.sequence;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        key = _ref1[_i];
        _results.push(fn(key, this.rules[key], this.priority.hasOwnProperty(key)));
      }
      return _results;
    };

    return RuleMap;

  })(RuleMap);

}).call(this);

/*
//@ sourceMappingURL=RuleMap.map
*/
