// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 [Stephan Jorek](stephan.jorek@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var exports, _create, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  _create = function(ParentClass) {
    var ExpressionMap, _ref1;
    ExpressionMap = ExpressionMap = (function(_super) {
      var parse;

      __extends(ExpressionMap, _super);

      function ExpressionMap() {
        _ref1 = ExpressionMap.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      parse = null;

      ExpressionMap.prototype.operator = {
        name: 'rules'
      };

      ExpressionMap.prototype.apply = function(string) {
        if (parse == null) {
          parse = require('./Parser').parse;
        }
        return this.inject(parse(string, this));
      };

      ExpressionMap.prototype.normalizeValue = function(expression) {
        return expression;
      };

      ExpressionMap.prototype.toJSON = function(callback) {
        if (callback) {
          return callback(this);
        }
        return this.flatten();
      };

      ExpressionMap.prototype.callback = function(callback) {
        return this.each(function(key, expression, important) {
          return expression.callback(callback);
        });
      };

      ExpressionMap.prototype.evaluate = function(context, variables, scope, stack) {
        var rules;
        if (context == null) {
          context = {};
        }
        if (variables == null) {
          variables = {};
        }
        rules = {};
        this.map(function(key, expression, important) {
          return rules[key] = expression.evaluate(context, variables, scope, stack);
        });
        return rules;
      };

      return ExpressionMap;

    })(ParentClass);
    return ExpressionMap;
  };

  exports.Expressions = _create(require("./Ordered/PropertyMap").PropertyMap);

}).call(this);

/*
//@ sourceMappingURL=Expressions.map
*/
