// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var GoateeRules, exports, _ref;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.GoateeRules = GoateeRules = (function() {
    function GoateeRules() {}

    GoateeRules.NAME = 'goatee-rules';

    GoateeRules.VERSION = '0.0.1';

    GoateeRules.parse = (function() {
      var parse;
      parse = null;
      return function(code) {
        if (parse == null) {
          GoateeRules.parse = parse = require('./GoateeRules/Parser').parse;
        }
        return parse(code);
      };
    })();

    GoateeRules.evaluate = function(code, context, variables, scope, stack) {
      return GoateeRules.parse(code).evaluate(context, variables, scope, stack);
    };

    GoateeRules.render = (function() {
      var render;
      render = null;
      return function(code) {
        if (render == null) {
          GoateeRules.render = render = require('./GoateeRules/Compiler').Compiler.render;
        }
        return render(code);
      };
    })();

    GoateeRules.ast = (function() {
      var ast;
      ast = null;
      return function(data, callback, compress) {
        if (ast == null) {
          GoateeRules.ast = ast = require('./GoateeRules/Compiler').Compiler.ast;
        }
        return ast(data, callback, compress);
      };
    })();

    GoateeRules.stringify = (function() {
      var stringify;
      stringify = null;
      return function(data, callback, compress) {
        if (stringify == null) {
          GoateeRules.stringify = stringify = require('./GoateeRules/Compiler').Compiler.stringify;
        }
        return stringify(data, callback, compress);
      };
    })();

    GoateeRules.compile = (function() {
      var compile;
      compile = null;
      return function(data, callback, compress) {
        if (compile == null) {
          GoateeRules.compile = compile = require('./GoateeRules/Compiler').Compiler.compile;
        }
        return compile(data, callback, compress);
      };
    })();

    return GoateeRules;

  })();

}).call(this);

/*
//@ sourceMappingURL=GoateeRules.map
*/
